Gets Highlight Timestamps
mattlianje/gregarious-wolf pull request #56
Opened 2020-03-24 17:35 UTC by Eldrick19

- Saves highlight timestamps as list of lists for specific URL
- Two results: timestamps for RF and timestamps for NN
- Currently hard-coded URL but different URL can be passed

Should I be sending the variables anywhere? Right now they're just sitting

2020-03-25 04:27 UTC, tjlam requested changes
Looks good just some small changes

2020-03-25 04:27 UTC, tjlam commented on post-processing/getHighlightTimestamps.py
> +
add `db_conn.dispose()` to close the connection

2020-03-25 04:27 UTC, tjlam commented on post-processing/getHighlightTimestamps.py
> +
Bit of an edge case: If the last x rows are highlights then they wouldn't be added to the array.

2020-03-25 04:27 UTC, tjlam commented on post-processing/getHighlightTimestamps.py
> +nn_timestamps
Lets convert these arrays to a numpy array, and write them to a file named`videoId.npy`

2020-03-26 01:13 UTC, mattlianje reviewed
LGTM <3 just a small boi and Lam's stuff

2020-03-26 01:13 UTC, mattlianje commented on post-processing/getHighlightTimestamps.py
> +for index, row in df.iterrows():
`for row in df.iterrows():` should do it

2020-03-26 01:13 UTC, mattlianje commented on post-processing/getHighlightTimestamps.py
> +nn_timestamps
@Eldrick19 @tjlam good point - this got me thinking for moving on ... these highlights should be either in some db ...
or if we keep using npy files ... to an s3 bucket ... so tangentially related is this helper #57

2020-03-26 16:58 UTC, Eldrick19 commented on post-processing/getHighlightTimestamps.py
> +
Good catch. Fixed in the latest push

2020-03-26 16:58 UTC, Eldrick19 commented on post-processing/getHighlightTimestamps.py
> +
Good catch. Fixed in the latest push

2020-03-26 17:00 UTC, Eldrick19 commented on post-processing/getHighlightTimestamps.py
> +nn_timestamps
I agree. I saved them to `.npz` files for now (its like a `.npy` file but for more than one array). They are ID'd based off of the URL. Lemme know if we should identify them differently.

2020-03-26 17:00 UTC, Eldrick19 commented on post-processing/getHighlightTimestamps.py
> +for index, row in df.iterrows():
With the new changes this make my code crash :/

2020-03-28 00:10 UTC, tjlam approved these changes
LGTM

2020-03-28 04:31 UTC, mattlianje commented on post-processing/getHighlightTimestamps.py
> +for index, row in df.iterrows():
mmmm - nvm then) The new way you implemented is nice and more intuitive))

2020-03-28 04:33 UTC, mattlianje approved these changes
LGTM

2020-03-28 23:06 UTC, merged